/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 101 */
/* metalib md5sum: f8305675cf6b3330d5923f3f17b6f7be */

/* creation time: Thu Aug 18 18:14:29 2016 */
/* tdr version: 2.7.12, build at 20151212 */


namespace GSProtocal
{


public class MetaLib
{
 public static int getVersion()
 {
  return 101;
 }

 public static string getName()
 {
  return "GSProtocal";
 }

 public static string getMd5Sum()
 {
  return "f8305675cf6b3330d5923f3f17b6f7be";
 }

 public static string getTdrVersion()
 {
  return "2.7.12, build at 20151212";
 }
}


}
